[build]
command = "bun run build"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "false"
BUN_VERSION = "1.0.25"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/*"
to = "/"
status = 200