import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import type React from "react";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const serviceLinks = [
  { name: "Excavation", slug: "excavation" },
  { name: "Demolition", slug: "demolition" },
  { name: "Land Clearing & Grading", slug: "land-clearing-grading" },
  { name: "Utility Installation", slug: "utility-installation" },
  { name: "Foundation Work", slug: "foundation-work" },
  { name: "Concrete", slug: "concrete" },
  { name: "Septic & Sewer", slug: "septic-sewer" },
  { name: "Rock & Sand Delivery", slug: "rock-sand-delivery" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <head>
        <title>H&I Construction | Kennewick & Tri-Cities WA</title>
        <meta
          name="description"
          content="H&I Construction serves Kennewick, Tri-Cities, Walla Walla, Yakima, Grandview, Prosser, Sunnyside, and more with expert excavation, demolition, land clearing, utilities, foundations, concrete, septic, and delivery services. Licensed local contractor for residential and commercial projects."
        />
        <meta
          name="keywords"
          content="Kennewick WA construction, Tri-Cities contractor, excavation, demolition, land clearing, grading, utility installation, foundation, concrete, septic, sewer, rock, sand delivery, Walla Walla, Yakima, Sunnyside, Prosser, Grandview"
        />
        <meta property="og:title" content="H&I Construction | Kennewick & Tri-Cities WA" />
        <meta property="og:description" content="Expert excavation, demolition, concrete, septic, and more for Kennewick, Tri-Cities, and beyond." />
        <meta property="og:type" content="website" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              '@context': 'https://schema.org',
              '@type': 'LocalBusiness',
              'name': 'H&I Construction LLC',
              'url': 'https://handiconstruction.com',
              'telephone': '(509) 123-4567',
              'email': 'info@handiconstruction.com',
              'address': {
                '@type': 'PostalAddress',
                'streetAddress': '123 Main St',
                'addressLocality': 'Kennewick',
                'addressRegion': 'WA',
                'postalCode': '99336',
                'addressCountry': 'US'
              },
              'openingHoursSpecification': [
                {
                  '@type': 'OpeningHoursSpecification',
                  'dayOfWeek': [
                    'Monday',
                    'Tuesday',
                    'Wednesday',
                    'Thursday',
                    'Friday'
                  ],
                  'opens': '07:00',
                  'closes': '17:00'
                },
                {
                  '@type': 'OpeningHoursSpecification',
                  'dayOfWeek': 'Saturday',
                  'opens': '08:00',
                  'closes': '14:00'
                }
              ],
              'areaServed': [
                'Kennewick',
                'Pasco',
                'Richland',
                'West Richland',
                'Walla Walla',
                'Yakima',
                'Grandview',
                'Prosser',
                'Sunnyside'
              ],
              'sameAs': [
                'https://facebook.com/profile.php?id=100089345247566',
                'https://www.instagram.com/handiconstructionllc/'
              ]
            })
          }}
        />
      </head>
      <body className="bg-white text-black min-h-screen flex flex-col antialiased">
        <header className="sticky top-0 z-50 bg-white shadow border-b border-slate-200">
          <nav className="relative max-w-7xl mx-auto flex items-center justify-between px-4 h-16">
            <div className="flex items-center flex-shrink-0 mr-6">
              <Link href="/" className="flex items-center gap-2">
                <span className="inline-block w-9 h-9 bg-slate-200 rounded mr-2 flex items-center justify-center font-extrabold text-2xl text-[#0B1E4A]">
                  H&I
                </span>
                <span className="text-[#0B1E4A] text-xl font-extrabold tracking-wide hidden sm:block">
                  H&I Construction
                </span>
              </Link>
            </div>
            <ul className="hidden md:flex items-center space-x-4">
              <li>
                <Link
                  href="/"
                  className="px-3 py-2 rounded hover:bg-blue-100 font-semibold transition"
                >
                  Home
                </Link>
              </li>
              <li className="relative group px-3 py-2">
                <button className="font-semibold hover:bg-blue-100 px-3 py-2 rounded transition flex items-center gap-1 focus:outline-none">
                  Services{" "}
                  <svg
                    className="w-4 h-4 inline"
                    viewBox="0 0 20 20"
                  >
                    <path
                      d="M5.8 8.2l4.2 4.2 4.2-4.2"
                      stroke="#0B1E4A"
                      strokeWidth="2"
                      fill="none"
                      strokeLinecap="round"
                    />
                  </svg>
                </button>
                <ul className="absolute left-0 mt-2 min-w-[220px] rounded bg-white border shadow-lg opacity-0 group-hover:opacity-100 pointer-events-none group-hover:pointer-events-auto transition-all">
                  {serviceLinks.map((service) => (
                    <li key={service.slug}>
                      <Link
                        href={`/services/${service.slug}`}
                        className="block px-5 py-2 hover:bg-blue-50 text-[#0B1E4A] font-medium"
                      >
                        {service.name}
                      </Link>
                    </li>
                  ))}
                </ul>
              </li>
              <li>
                <Link
                  href="/about-us"
                  className="px-3 py-2 rounded hover:bg-blue-100 font-semibold transition"
                >
                  About Us
                </Link>
              </li>
              <li>
                <Link
                  href="/contact"
                  className="px-3 py-2 rounded hover:bg-blue-100 font-semibold transition"
                >
                  Contact
                </Link>
              </li>
            </ul>
            {/* Mobile menu trigger and structure (functional in next step) */}
            <div className="md:hidden">
              {/* [Mobile menu logic will be added here] */}
              <button
                aria-label="Open mobile menu"
                className="p-2 rounded hover:bg-blue-100"
              >
                <svg
                  viewBox="0 0 24 24"
                  width="28"
                  height="28"
                  fill="none"
                  stroke="#0B1E4A"
                  strokeWidth="2"
                >
                  <line x1="3" y1="6" x2="21" y2="6" />
                  <line x1="3" y1="12" x2="21" y2="12" />
                  <line x1="3" y1="18" x2="21" y2="18" />
                </svg>
              </button>
            </div>
          </nav>
        </header>
        <main className="flex-1 w-full">{children}</main>
        <footer className="bg-[#0B1E4A] text-white text-sm py-8 mt-12">
          <div className="max-w-7xl mx-auto px-4 flex flex-col md:flex-row md:justify-between gap-8">
            <div className="flex flex-col gap-2">
              <div className="flex items-center space-x-4">
                <a
                  href="https://facebook.com/profile.php?id=100089345247566"
                  target="_blank"
                  rel="noreferrer noopener"
                  aria-label="Facebook"
                  className="hover:text-blue-300 transition"
                >
                  <svg
                    width="28"
                    height="28"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path d="M22.675 0h-21.35C.595 0 0 .592 0 1.326v21.348C0 23.406.593 24 1.326 24H12.82v-9.294H9.692V11.01h3.128V8.413c0-3.1 1.894-4.788 4.659-4.788 1.325 0 2.462.099 2.797.142v3.24h-1.918c-1.504 0-1.797.714-1.797 1.763v2.312h3.587l-.467 3.696h-3.12V24h6.116c.73 0 1.324-.593 1.324-1.326V1.326C24 .592 23.406 0 22.675 0" />
                  </svg>
                </a>
                <a
                  href="https://www.instagram.com/handiconstructionllc/"
                  target="_blank"
                  rel="noreferrer noopener"
                  aria-label="Instagram"
                  className="hover:text-blue-300 transition"
                >
                  <svg
                    width="28"
                    height="28"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path d="M12 2.163c3.204 0 3.584.012 4.849.07 1.366.062 2.633.341 3.608 1.316.975.974 1.254 2.241 1.316 3.608.058 1.265.069 1.645.069 4.849s-.012 3.584-.07 4.849c-.062 1.366-.341 2.633-1.316 3.608-.974.975-2.241 1.254-3.608 1.316-1.265.058-1.645.069-4.849.069s-3.584-.012-4.849-.07c-1.366-.062-2.633-.341-3.608-1.316C2.39 19.295 2.11 18.028 2.049 16.661c-.058-1.265-.069-1.645-.069-4.849s.012-3.584.07-4.849C2.11 4.705 2.39 3.438 3.364 2.464c.975-.975 2.241-1.254 3.608-1.316C8.416 2.175 8.796 2.163 12 2.163zm0-2.163C8.735 0 8.332.013 7.052.072c-1.672.073-3.072.38-4.17 1.478C2.004 2.694 1.697 4.093 1.624 5.765.563 7.044.551 7.447.551 12c0 4.553.012 4.956 1.073 6.235.073 1.672.38 3.071 1.478 4.169C2.694 21.996 4.093 22.303 5.765 22.376c1.271.059 1.674.072 6.235.072s4.956-.013 6.235-.072c1.672-.073 3.071-.38 4.169-1.478 1.097-1.097 1.405-2.497 1.478-4.169.059-1.27.072-1.673.072-6.234s-.013-4.965-.072-6.235C21.996 2.694 20.599 2.387 18.927 2.314c-1.27-.059-1.673-.072-6.234-.072zM12 5.838a6.164 6.164 0 100 12.327 6.164 6.164 0 000-12.327zm0 10.164a3.997 3.997 0 110-7.993 3.997 3.997 0 010 7.993zm6.406-11.845a1.44 1.44 0 100 2.881 1.44 1.44 0 000-2.881z" />
                  </svg>
                </a>
              </div>
              <span className="block font-medium text-lg mt-2">
                H&I Construction LLC
              </span>
              <p className="mt-4">
                Serving: Kennewick, Pasco, Richland, West Richland, Walla Walla,
                Yakima, Grandview, Prosser, Sunnyside, WA
              </p>
            </div>
            <div>
              <div className="font-bold mb-1">Hours of Operation</div>
              <div>
                Mon–Fri: 7:00 AM – 5:00 PM
                <br />
                Sat: 8:00 AM – 2:00 PM
                <br />
                Sun: Closed
              </div>
              <div className="font-bold mt-4 mb-1">Contact</div>
              <div>
                (509) 123-4567
                <br />
                info@handiconstruction.com
              </div>
            </div>
          </div>
          <div className="mt-8 text-center text-xs text-blue-100 opacity-70">
            &copy; {new Date().getFullYear()} H&amp;I Construction LLC. All
            rights reserved.
          </div>
        </footer>
      </body>
    </html>
  );
}
